package com.gojek.parkinglot.models;

public enum CommandEnum {
    CREATE_PARKING_LOT,
    PARK,
    LEAVE,
    STATUS,
    REGISTRATION_NUMBERS_FOR_CARS_WITH_COLOUR,
    SLOT_NUMBERS_FOR_CARS_WITH_COLOR,
    SLOT_NUMBERS_FOR_REGISTRATION_NUMBER;
}
